### ISSUE TITLE
Use correct trash path with `sudo`

### ISSUE THREAD

**Issue by kevva** [sindresorhus/osx-trash#2]
https://github.com/sindresorhus/trash/issues/21

**Comment by sindresorhus** [comment]
And it's not? :p If you sudo you're temporarily the root users, which means it goes to the root users trash.

Though I do agree it's not optimal. I'm honestly not sure how we would fix this as I'm just calling the native trash method.

Suggestions?

**Comment by kevva** [comment]
Yeah, I haven't been able to test it as `sudo` but it sounds like the expected behavior for me too.

**Comment by sindresorhus** [comment]
It's the expected behavior, but not the wanted.
