### ISSUE TITLE
Hidden folders get deleted instead of sent to trash

### ISSUE THREAD

**Issue by kevintraver** [sindresorhus/osx-trash#3]

**Comment by sindresorhus** [comment]
Hidden folder as in those starting with a dot (`.foo`)? Can you elaborate?

I just tried on OS X 10.10.5 and works fine for me:

<img width="294" alt="screen shot 2015-08-30 at 10 48 22" src="https://cloud.githubusercontent.com/assets/170270/9565608/c4c4f708-4f04-11e5-9164-3df1d8e28c83.png">

**Comment by kevintraver** [comment]
I'm on OS X 10.11 (beta), so maybe it's a bug in the latest OS

**Comment by kevintraver** [comment]
Ah, I see, they are actually in the Trash, but the trash icon still appears empty. Not sure if that is supposed to be by design, but obviously that's unrelated to osx-trash, so Ill close this issue.
